"""Ajout table matieres

Revision ID: 56aea08c7d66
Revises: c0cd9d10d2e0
Create Date: 2026-07-17 17:58:55.467135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56aea08c7d66'
down_revision = 'c0cd9d10d2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('famille', sa.String(length=50), nullable=False),
    sa.Column('durete_hb', sa.Float(), nullable=False),
    sa.Column('usinabilite', sa.Float(), nullable=False),
    sa.Column('conductivite_thermique', sa.Float(), nullable=True),
    sa.Column('densite', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matieres')
    # ### end Alembic commands ###
