"""Ajout des colonnes machine

Revision ID: 5f21cea10e58
Revises: 635d49376c42
Create Date: 2026-07-31 01:15:20.181464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f21cea10e58'
down_revision = '635d49376c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outil_id', sa.Integer(), nullable=False),
    sa.Column('etat_actuel', sa.String(length=5), nullable=False),
    sa.Column('etat_predit', sa.String(length=5), nullable=False),
    sa.Column('probabilite', sa.Float(), nullable=False),
    sa.Column('rul', sa.Float(), nullable=True),
    sa.Column('nombre_sessions_restantes', sa.Integer(), nullable=True),
    sa.Column('date_prediction', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outil_id'], ['outils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('heures_fonctionnement', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rigidite', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('coefficient_usure', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('puissance_kw', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitesse_max_broche', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('precision_mm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('precision_mm')
        batch_op.drop_column('vitesse_max_broche')
        batch_op.drop_column('puissance_kw')
        batch_op.drop_column('coefficient_usure')
        batch_op.drop_column('rigidite')
        batch_op.drop_column('heures_fonctionnement')
        batch_op.drop_column('age')

    op.drop_table('predictions')
    # ### end Alembic commands ###
