"""Ajout Damage Engine

Revision ID: 635d49376c42
Revises: 86b289ebcda0
Create Date: 2026-07-28 10:32:27.882404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635d49376c42'
down_revision = '86b289ebcda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etat_outils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outil_id', sa.Integer(), nullable=False),
    sa.Column('etat', sa.String(length=5), nullable=False),
    sa.Column('indice_sante', sa.Float(), nullable=False),
    sa.Column('derniere_mise_a_jour', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outil_id'], ['outils.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outil_id')
    )
    op.create_table('degats_outils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('outil_id', sa.Integer(), nullable=False),
    sa.Column('igso', sa.Float(), nullable=False),
    sa.Column('degats_session', sa.Float(), nullable=False),
    sa.Column('degats_cumules', sa.Float(), nullable=False),
    sa.Column('date_calcul', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['outil_id'], ['outils.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_usinage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('historique_etats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etat_outil_id', sa.Integer(), nullable=False),
    sa.Column('ancien_etat', sa.String(length=5), nullable=False),
    sa.Column('nouvel_etat', sa.String(length=5), nullable=False),
    sa.Column('raison', sa.String(length=255), nullable=True),
    sa.Column('date_transition', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etat_outil_id'], ['etat_outils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historique_etats')
    op.drop_table('degats_outils')
    op.drop_table('etat_outils')
    # ### end Alembic commands ###
