"""Creation table indices_calcules

Revision ID: 86b289ebcda0
Revises: d950dc939ce3
Create Date: 2026-07-28 10:18:48.107729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b289ebcda0'
down_revision = 'd950dc939ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indices_calcules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('indice_mecanique', sa.Float(), nullable=False),
    sa.Column('indice_thermique', sa.Float(), nullable=False),
    sa.Column('indice_machine', sa.Float(), nullable=False),
    sa.Column('indice_historique', sa.Float(), nullable=False),
    sa.Column('indice_parametres', sa.Float(), nullable=False),
    sa.Column('igso', sa.Float(), nullable=False),
    sa.Column('date_calcul', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_usinage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indices_calcules')
    # ### end Alembic commands ###
