"""Création table TypeOutil

Revision ID: 9a44a90d49d7
Revises: a3fb68846a74
Create Date: 2026-07-15 00:01:19.488068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a44a90d49d7'
down_revision = 'a3fb68846a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types_outils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('fabricant', sa.String(length=100), nullable=True),
    sa.Column('categorie', sa.Enum('FRAISE', 'FORET', 'TARAUD', 'ALESOIR', 'PLAQUETTE', name='categorieoutil'), nullable=False),
    sa.Column('diametre', sa.Float(), nullable=False),
    sa.Column('nb_dents', sa.Integer(), nullable=True),
    sa.Column('matiere', sa.String(length=100), nullable=True),
    sa.Column('revetement', sa.String(length=100), nullable=True),
    sa.Column('angle_helice', sa.Float(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('types_outils')
    # ### end Alembic commands ###
