"""Création table UAP

Revision ID: a3fb68846a74
Revises: be1394d184f5
Create Date: 2026-07-14 23:27:30.573569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3fb68846a74'
down_revision = 'be1394d184f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type_machine', sa.String(length=100), nullable=False),
    sa.Column('constructeur', sa.String(length=100), nullable=True),
    sa.Column('modele', sa.String(length=100), nullable=True),
    sa.Column('nb_axes', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('uaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    op.drop_table('uaps')
    op.drop_table('machines')
    # ### end Alembic commands ###
