"""Création table Outil

Revision ID: c78741167028
Revises: 9a44a90d49d7
Create Date: 2026-07-15 00:22:54.174845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78741167028'
down_revision = '9a44a90d49d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('type_outil_id', sa.Integer(), nullable=False),
    sa.Column('date_mise_service', sa.Date(), nullable=True),
    sa.Column('nb_affutages', sa.Integer(), nullable=False),
    sa.Column('dernier_affutage', sa.Date(), nullable=True),
    sa.Column('degats_cumules', sa.Float(), nullable=False),
    sa.Column('etat_actuel', sa.Enum('S0', 'S1', 'S2', 'S3', 'S4', name='etatoutil'), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['type_outil_id'], ['types_outils.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('numero_serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outils')
    # ### end Alembic commands ###
